package Objects.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEASURE".
 */
public class Measure {

    private Long id;
    private Float tempirature;
    private Float pressure;
    private Float current;
    private String time;

    public Measure() {
    }

    public Measure(Long id) {
        this.id = id;
    }

    public Measure(Long id, Float tempirature, Float pressure, Float current, String time) {
        this.id = id;
        this.tempirature = tempirature;
        this.pressure = pressure;
        this.current = current;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getTempirature() {
        return tempirature;
    }

    public void setTempirature(Float tempirature) {
        this.tempirature = tempirature;
    }

    public Float getPressure() {
        return pressure;
    }

    public void setPressure(Float pressure) {
        this.pressure = pressure;
    }

    public Float getCurrent() {
        return current;
    }

    public void setCurrent(Float current) {
        this.current = current;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
