package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANSWERS_U".
 */
public class AnswersU {

    private Long id;
    private Integer qid;
    private Integer sid;
    private Integer gid;
    private Integer u_sid;
    private String answer;
    private String code;

    public AnswersU() {
    }

    public AnswersU(Long id) {
        this.id = id;
    }

    public AnswersU(Long id, Integer qid, Integer sid, Integer gid, Integer u_sid, String answer, String code) {
        this.id = id;
        this.qid = qid;
        this.sid = sid;
        this.gid = gid;
        this.u_sid = u_sid;
        this.answer = answer;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQid() {
        return qid;
    }

    public void setQid(Integer qid) {
        this.qid = qid;
    }

    public Integer getSid() {
        return sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

    public Integer getU_sid() {
        return u_sid;
    }

    public void setU_sid(Integer u_sid) {
        this.u_sid = u_sid;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
