package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANSWERS_P".
 */
public class AnswersP {

    private String available_answers;
    private String subquestions;
    private String attributes;
    private String attributes_lang;

    public AnswersP() {
    }

    public AnswersP(String available_answers, String subquestions, String attributes, String attributes_lang) {
        this.available_answers = available_answers;
        this.subquestions = subquestions;
        this.attributes = attributes;
        this.attributes_lang = attributes_lang;
    }

    public String getAvailable_answers() {
        return available_answers;
    }

    public void setAvailable_answers(String available_answers) {
        this.available_answers = available_answers;
    }

    public String getSubquestions() {
        return subquestions;
    }

    public void setSubquestions(String subquestions) {
        this.subquestions = subquestions;
    }

    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    public String getAttributes_lang() {
        return attributes_lang;
    }

    public void setAttributes_lang(String attributes_lang) {
        this.attributes_lang = attributes_lang;
    }

}
