package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANSWERS".
 */
public class Answers {

    private Long id;
    private Integer qid;
    private String answer;
    private Integer assessment_value;
    private Integer scale_id;
    private String code;

    public Answers() {
    }

    public Answers(Long id) {
        this.id = id;
    }

    public Answers(Long id, Integer qid, String answer, Integer assessment_value, Integer scale_id, String code) {
        this.id = id;
        this.qid = qid;
        this.answer = answer;
        this.assessment_value = assessment_value;
        this.scale_id = scale_id;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQid() {
        return qid;
    }

    public void setQid(Integer qid) {
        this.qid = qid;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Integer getAssessment_value() {
        return assessment_value;
    }

    public void setAssessment_value(Integer assessment_value) {
        this.assessment_value = assessment_value;
    }

    public Integer getScale_id() {
        return scale_id;
    }

    public void setScale_id(Integer scale_id) {
        this.scale_id = scale_id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
