package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP".
 */
public class Group {

    private Long id;
    private Integer sid;
    private String group_name;
    private String description;
    private String language;
    private Integer group_order;
    private String randomization_group;
    private String grelevance;

    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, Integer sid, String group_name, String description, String language, Integer group_order, String randomization_group, String grelevance) {
        this.id = id;
        this.sid = sid;
        this.group_name = group_name;
        this.description = description;
        this.language = language;
        this.group_order = group_order;
        this.randomization_group = randomization_group;
        this.grelevance = grelevance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSid() {
        return sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Integer getGroup_order() {
        return group_order;
    }

    public void setGroup_order(Integer group_order) {
        this.group_order = group_order;
    }

    public String getRandomization_group() {
        return randomization_group;
    }

    public void setRandomization_group(String randomization_group) {
        this.randomization_group = randomization_group;
    }

    public String getGrelevance() {
        return grelevance;
    }

    public void setGrelevance(String grelevance) {
        this.grelevance = grelevance;
    }

}
