package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURVEY_U".
 */
public class SurveyU {

    private Long id;
    private Integer sid;
    private String date;
    private String active;
    private String title;

    public SurveyU() {
    }

    public SurveyU(Long id) {
        this.id = id;
    }

    public SurveyU(Long id, Integer sid, String date, String active, String title) {
        this.id = id;
        this.sid = sid;
        this.date = date;
        this.active = active;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSid() {
        return sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
