package com.android.acusurvey.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURVEYS".
 */
public class Surveys {

    private Long id;
    private String surveyls_title;
    private String format;
    private String value;

    public Surveys() {
    }

    public Surveys(Long id) {
        this.id = id;
    }

    public Surveys(Long id, String surveyls_title, String format, String value) {
        this.id = id;
        this.surveyls_title = surveyls_title;
        this.format = format;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSurveyls_title() {
        return surveyls_title;
    }

    public void setSurveyls_title(String surveyls_title) {
        this.surveyls_title = surveyls_title;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
